Init api-server, init discord auth
alteh-union/org-helper pull request #26
Opened 2020-10-18 20:01 UTC by Nau077

Add express deps. to make start making api
Add nodemon to make hotheload dev work
Add auth login route "/auth/login" which realize discord oath2 redirect and return grant code (about outh2 https://discord.com/developers/docs/topics/oauth2 more information)

2020-10-19 20:20 UTC, alteh-union requested changes

2020-10-19 20:20 UTC, alteh-union commented on src/api/init-api.js
> +
Can we assign the context object ("c") to app.locals here?

In this case you will not need to initialize prefsManager every time in src/api/controllers/auth.js file, and instead just access it through req.app.locals.c.prefsManager. By the way, I would suggest to rename "c" to "context" here and in app.locals, for better readability.

This also should become helpful in the future, when you call other context objects from the routes (like commands-parser.js).

For further reading on the topic:
https://expressjs.com/ru/api.html
https://stackoverflow.com/questions/28748337/whats-the-best-way-to-access-the-express-app-object-from-inside-a-separate-ro

2020-10-21 10:56 UTC, Nau077 commented on preferences_template.xml
>  db_port = 27017
I forgot about it. It was happend when I first time started running project

Will fixed it

2020-10-21 15:18 UTC, Nau077 commented on preferences_template.xml
> +server_port = 4000
fix it

2020-10-22 06:27 UTC, merged